baseURL = "https://stephaniedaugherty.com/"
languageCode = "en-us"
title = "My Blog"
theme = "mero"
disableKinds = ["taxonomyTerm"]

[params]
  dateFormat = "2006-01-02" 
  author = "Stephanie"
  description = "My random thoughts"
  mainImage = "images/main.jpeg"

[params.introduction]
   text = "**This website** is my blog."

[params.social]

  [[params.social.list]]
  class = "fab"
  icon = "fa-twitter"
  url = "https://twitter.com/stephdaugherty"


[params.footer]
  message = "&copy; 2021 Stephanie Daugherty"
